FROM node:20-bookworm-slim AS build
ENV npm_config_fetch_retry_maxtimeout=120000 \
    npm_config_fetch_retries=5 \
    npm_config_fetch_retry_mintimeout=2000
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund
COPY . .
RUN test -f .env.production && cat .env.production || true
RUN npm run build

FROM nginx:alpine
# Install envsubst for templating Nginx config at runtime
RUN apk add --no-cache gettext
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
CMD sh -c 'envsubst '\''$PORT'\'' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
