FROM nginx:alpine
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY dist /usr/share/nginx/html
CMD ["sh","-c","envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
