version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: rating
      POSTGRES_DB: rating
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rating"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  rating-api:
    build: ./rating-api
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 4000
      DATABASE_URL: postgres://rating:example@postgres:5432/rating
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
